"""GLSL type system for shadekit.

Provides type descriptors for all GLSL built-in types, a ``@glsl_struct``
decorator for generating struct declarations from Python dataclasses,
and type-inference utilities for binary operations and constructors.

Quick start::

    from shadekit.types import Vec3, Float, Mat4, glsl_struct
    from dataclasses import dataclass

    @glsl_struct
    @dataclass
    class Material:
        albedo: Vec3
        roughness: Float
        metallic: Float

    print(Material.__glsl_declaration__)
"""

from ._arrays import ArrayType
from ._base import ShaderMeta, ShaderType
from ._inference import infer_binary_type, validate_constructor
from ._matrices import Mat2, Mat3, Mat4, MatrixType

# Samplers
from ._samplers import (
    AtomicUint,
    IImage1D,
    IImage2D,
    IImage2DArray,
    IImage3D,
    IImageCube,
    Image1D,
    Image1DArray,
    Image2D,
    Image2DArray,
    Image2DMS,
    Image3D,
    ImageBuffer,
    ImageCube,
    ImageCubeArray,
    ImageType,
    ISampler1D,
    ISampler1DArray,
    ISampler2D,
    ISampler2DArray,
    ISampler2DMS,
    ISampler3D,
    ISamplerBuffer,
    ISamplerCube,
    ISamplerCubeArray,
    Sampler1D,
    Sampler1DArray,
    Sampler1DArrayShadow,
    Sampler1DShadow,
    Sampler2D,
    Sampler2DArray,
    Sampler2DArrayShadow,
    Sampler2DMS,
    Sampler2DMSArray,
    Sampler2DRect,
    Sampler2DRectShadow,
    Sampler2DShadow,
    Sampler3D,
    SamplerBuffer,
    SamplerCube,
    SamplerCubeArray,
    SamplerCubeArrayShadow,
    SamplerCubeShadow,
    SamplerType,
    UImage1D,
    UImage2D,
    UImage2DArray,
    UImage3D,
    UImageCube,
    USampler1D,
    USampler1DArray,
    USampler2D,
    USampler2DArray,
    USampler2DMS,
    USampler3D,
    USamplerBuffer,
    USamplerCube,
    USamplerCubeArray,
    Void,
)
from ._scalars import Bool, Double, Float, Int, ScalarType, UInt
from ._structs import StructType, shader_struct
from ._vectors import (
    BVec2,
    BVec3,
    BVec4,
    DVec2,
    DVec3,
    DVec4,
    IVec2,
    IVec3,
    IVec4,
    UVec2,
    UVec3,
    UVec4,
    Vec2,
    Vec3,
    Vec4,
    VectorType,
)

__all__ = [
    "ShaderMeta",
    "ShaderType",
    "ScalarType",
    "Float",
    "Double",
    "Int",
    "UInt",
    "Bool",
    "VectorType",
    "Vec2",
    "Vec3",
    "Vec4",
    "DVec2",
    "DVec3",
    "DVec4",
    "IVec2",
    "IVec3",
    "IVec4",
    "UVec2",
    "UVec3",
    "UVec4",
    "BVec2",
    "BVec3",
    "BVec4",
    "MatrixType",
    "Mat2",
    "Mat3",
    "Mat4",
    "SamplerType",
    "Sampler1D",
    "Sampler2D",
    "Sampler3D",
    "SamplerCube",
    "Sampler2DArray",
    "Sampler1DArray",
    "SamplerCubeArray",
    "SamplerBuffer",
    "Sampler2DMS",
    "Sampler2DMSArray",
    "Sampler2DRect",
    "ISampler1D",
    "ISampler2D",
    "ISampler3D",
    "ISamplerCube",
    "ISampler2DArray",
    "ISampler1DArray",
    "ISamplerCubeArray",
    "ISamplerBuffer",
    "ISampler2DMS",
    "USampler1D",
    "USampler2D",
    "USampler3D",
    "USamplerCube",
    "USampler2DArray",
    "USampler1DArray",
    "USamplerCubeArray",
    "USamplerBuffer",
    "USampler2DMS",
    "Sampler1DShadow",
    "Sampler2DShadow",
    "SamplerCubeShadow",
    "Sampler1DArrayShadow",
    "Sampler2DArrayShadow",
    "SamplerCubeArrayShadow",
    "Sampler2DRectShadow",
    "ImageType",
    "Image1D",
    "Image2D",
    "Image3D",
    "ImageCube",
    "Image2DArray",
    "Image1DArray",
    "ImageCubeArray",
    "ImageBuffer",
    "Image2DMS",
    "IImage1D",
    "IImage2D",
    "IImage3D",
    "IImageCube",
    "IImage2DArray",
    "UImage1D",
    "UImage2D",
    "UImage3D",
    "UImageCube",
    "UImage2DArray",
    "AtomicUint",
    "Void",
    "ArrayType",
    "StructType",
    "shader_struct",
    "infer_binary_type",
    "validate_constructor",
]
